language: android
android:
  components:
  - platform-tools
  - tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-+
