language: android
android:
  components:
  - platform-tools
  - tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - addon-google_apis-google-+
before_install:
  - chmod +x gradlew
